version: '3.4'

services:

  db:
    image: postgres:alpine
    restart: always
    environment:
      POSTGRES_DB: counter_db
      POSTGRES_USER: counter
      POSTGRES_PASSWORD: password
    ports:
      - 5432:5432

  counter:
    image: korservick/grpc_counter:latest
    restart: always
    depends_on:
      - db
    ports:
      - 50051:50051
    environment:
      DB_HOST: db
